INSERT INTO BOOKS (ID,AUTHOR,ISBN,PUBLISH_DATE,TITLE) VALUES (2,'Test Author 2','Testısbn2','2001-01-01','Test kitap 2');
INSERT INTO BOOKS (ID,AUTHOR,ISBN,PUBLISH_DATE,TITLE) VALUES (3,'Test Author 3','Testısbn3','2001-01-01','Test kitap 3');
INSERT INTO BOOKS (ID,AUTHOR,ISBN,PUBLISH_DATE,TITLE) VALUES (4,'Test Author 4','Testısbn4','2001-01-01','Test kitap 4');
INSERT INTO BOOKS (ID,AUTHOR,ISBN,PUBLISH_DATE,TITLE) VALUES (5,'Test Author 5','Testısbn5','2001-01-01','Test kitap 5');
INSERT INTO BOOKS (ID,AUTHOR,ISBN,PUBLISH_DATE,TITLE) VALUES (6,'Test Author 6','Testısbn6','2001-01-01','Test kitap 6');