version: '27.3'
services:
  spboot-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=yakub
      - RABBITMQ_DEFAULT_PASS=yakub